const config = window.PORTFOLIO_CONFIG || {};
const userFromDomain = location.hostname.endsWith(".github.io") ? location.hostname.split(".")[0] : "";
let username = config.username || userFromDomain;
const grid = document.querySelector("#projects-grid");
const error = document.querySelector("#projects-error");
let language = localStorage.getItem("portfolio-language") || "ar";
let profileRequest = 0;

const copy = {
  ar: { navAbout:"عني",navProjects:"المشاريع",navContact:"تواصل",eyebrow:"مطور / صانع تجارب رقمية",heroTitle:"أحوّل الأفكار إلى<br><em>واجهات لها أثر.</em>",heroCopy:"أصمّم وأبني تجارب ويب سريعة وواضحة، مع اهتمام بالتفاصيل التي تجعل المنتج سهل الاستخدام ولا يُنسى.",explore:"استكشف المشاريع <span>↙</span>",quickChat:"محادثة سريعة ↗",aboutLabel:"01 / عني",projectsLabel:"02 / أعمال مختارة",projectsTitle:"مشاريع من GitHub",projectsNote:"يتم تحميل أحدث المستودعات والأشهر تلقائيًا.",loading:"جارِ تحميل المشاريع",latest:"الأحدث",popular:"الأشهر",contactLabel:"03 / لنبدأ",contactTitle:"هل لديك فكرة<br>تستحق أن تُبنى؟",rights:"جميع الحقوق محفوظة",updated:"آخر تحديث",setup:"أضف github_username في about.ar.md ليتم عرض مشاريعك هنا.",fail:"تعذر تحميل المشاريع. حاول لاحقاً.",visit:"زيارة الخدمة",source:"المستودع",defaultDescription:"مشروع مفتوح المصدر — اطلع على الكود من GitHub." },
  en: { navAbout:"About",navProjects:"Projects",navContact:"Contact",eyebrow:"DEVELOPER / DIGITAL MAKER",heroTitle:"I turn ideas into<br><em>interfaces that matter.</em>",heroCopy:"I design and build fast, clear web experiences with attention to the details that make a product useful and memorable.",explore:"Explore projects <span>↙</span>",quickChat:"Quick chat ↗",aboutLabel:"01 / ABOUT",projectsLabel:"02 / SELECTED WORK",projectsTitle:"Projects from GitHub",projectsNote:"Latest and most-starred repositories, loaded automatically.",loading:"Loading projects",latest:"Latest",popular:"Most popular",contactLabel:"03 / LET'S START",contactTitle:"Have an idea<br>worth building?",rights:"All rights reserved",updated:"Updated",setup:"Add github_username to about.md to show your projects here.",fail:"Unable to load projects. Please try again later.",visit:"Visit service",source:"Repository",defaultDescription:"An open-source project. Explore the code on GitHub." }
};
const t = key => copy[language][key];
const escapeHtml = value => { const node = document.createElement("div"); node.textContent = value || ""; return node.innerHTML; };
const validUrl = value => { try { const url = new URL(value); return ["https:","http:"].includes(url.protocol) ? url.href : ""; } catch { return ""; } };
function decodeBase64(value) { const bytes = Uint8Array.from(atob(value.replace(/\n/g,"")), char => char.charCodeAt(0)); return new TextDecoder().decode(bytes); }
function parseDocument(markdown) {
  const match = markdown.match(/^---\s*\n([\s\S]*?)\n---\s*\n?([\s\S]*)$/);
  const fields = {};
  if (match) match[1].split("\n").forEach(line => { const separator=line.indexOf(":"); if(separator > -1) fields[line.slice(0,separator).trim()]=line.slice(separator+1).trim().replace(/^['"]|['"]$/g,""); });
  return { fields, content: match ? match[2] : markdown };
}
function renderMarkdown(source) { const safe=source.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;"); return safe.split(/\n\n+/).map(block=>{ if(/^# /.test(block)) return `<h2>${block.slice(2)}</h2>`; if(/^## /.test(block)) return `<h3>${block.slice(3)}</h3>`; if(/^[-*] /m.test(block)) return `<ul>${block.split("\n").filter(x=>/^[-*] /.test(x)).map(x=>`<li>${x.slice(2)}</li>`).join("")}</ul>`; return `<p>${block.replace(/\*\*(.+?)\*\*/g,"<strong>$1</strong>").replace(/\n/g,"<br>")}</p>`; }).join(""); }
function parseProjectAbout(markdown) { const {fields,content}=parseDocument(markdown); return { serviceUrl:validUrl(fields.service_url), repositoryUrl:validUrl(fields.repository_url), description:content.replace(/^#+\s.*$/gm,"").replace(/[*_`>#]/g,"").replace(/\n+/g," ").trim() }; }
async function getProjectAbout(repo) { try { const response=await fetch(`https://api.github.com/repos/${encodeURIComponent(repo.owner.login)}/${encodeURIComponent(repo.name)}/contents/about.md`,{headers:{Accept:"application/vnd.github+json"}}); if(!response.ok) return {}; return parseProjectAbout(decodeBase64((await response.json()).content)); } catch { return {}; } }
async function card(repo,index) { const about=await getProjectAbout(repo), description=about.description || repo.description || t("defaultDescription"),date=new Intl.DateTimeFormat(language,{month:"short",year:"numeric"}).format(new Date(repo.updated_at)),repositoryUrl=about.repositoryUrl || repo.html_url,service=about.serviceUrl ? `<a class="project-action project-service" href="${about.serviceUrl}" target="_blank" rel="noreferrer">${t("visit")} ↗</a>` : ""; const details=`project.html?owner=${encodeURIComponent(repo.owner.login)}&repo=${encodeURIComponent(repo.name)}`; return `<article class="project-card"><div class="project-number">0${index+1}</div><div class="project-main"><div class="project-top"><span class="language">${escapeHtml(repo.language || "Code")}</span></div><h3>${escapeHtml(repo.name)}</h3><p>${escapeHtml(description)}</p></div><div class="project-actions"><a class="project-action" href="${details}">${language === "ar" ? "التفاصيل ←" : "View project →"}</a>${service}<a class="project-action" href="${repositoryUrl}" target="_blank" rel="noreferrer">${t("source")} ↗</a></div><div class="project-meta"><span>★ ${repo.stargazers_count}</span><span>${t("updated")} ${date}</span></div></article>`; }
async function loadProjects() { if(!username) { grid.innerHTML=""; error.hidden=false; error.textContent=t("setup"); return; } error.hidden=true; grid.innerHTML=`<div class="loader"><i></i><i></i><i></i> ${t("loading")}</div>`; try { const result=await fetch(`https://api.github.com/users/${encodeURIComponent(username)}/repos?sort=updated&per_page=100`,{headers:{Accept:"application/vnd.github+json"}}); if(!result.ok) throw new Error(); const repos=(await result.json()).filter(r=>!(config.hideForks && r.fork)).filter(r=>!(config.hideArchived && r.archived)); if(!repos.length) throw new Error(); const amount=config.maxProjects || 3,latest=repos.slice(0,amount),popular=[...repos].sort((a,b)=>b.stargazers_count-a.stargazers_count).slice(0,amount),displayed=[...new Map([...latest,...popular].map(repo=>[repo.id,repo])).values()],cards=new Map(await Promise.all(displayed.map(async(repo,index)=>[repo.id,await card(repo,index)]))); grid.innerHTML=`<h3 class="repo-group-title">${t("latest")}</h3>${latest.map(repo=>cards.get(repo.id)).join("")}<h3 class="repo-group-title">${t("popular")}</h3>${popular.map(repo=>cards.get(repo.id)).join("")}`; } catch { grid.innerHTML=""; error.hidden=false; error.textContent=t("fail"); } }
function applyProfile(fields) {
  const value=(key,fallback="")=>fields[key] || fallback;
  username=value("github_username",config.username || userFromDomain); const name=value("name","Snono-Dev"),email=value("email",config.email),sessionId=value("session_id","");
  document.title=`${name} | ${value("role",config.role || "Web Developer")}`; document.querySelector("#brand-name").textContent=name;
  document.querySelector("#hero-eyebrow").textContent=value("eyebrow",t("eyebrow")); document.querySelector("#hero-title").innerHTML=`${escapeHtml(value("hero_title","")).replace(/\n/g,"<br>")}<br><em>${escapeHtml(value("hero_emphasis","")).replace(/\n/g,"<br>")}</em>`;
  if(!fields.hero_title && !fields.hero_emphasis) document.querySelector("#hero-title").innerHTML=t("heroTitle"); document.querySelector("#hero-copy").textContent=value("hero_copy",t("heroCopy"));
  document.querySelector(".email-link").href=`mailto:${email}`; document.querySelector(".email-link").firstChild.textContent=`${email} `; document.querySelectorAll(".github-profile").forEach(link=>link.href=username ? `https://github.com/${username}` : "https://github.com");
  const chat=document.querySelector("#quick-chat"); chat.hidden=!sessionId; if(sessionId) chat.href="session.html";
  const skills=value("skills","").split(",").map(s=>s.trim()).filter(Boolean); document.querySelector("#skills").innerHTML=skills.map(skill=>`<span>${escapeHtml(skill)}</span>`).join("");
}
async function loadAbout() { const request=++profileRequest; try { let response=await fetch(language === "ar" ? "about.ar.md" : "about.md"); if(!response.ok && language === "ar") response=await fetch("about.md"); if(!response.ok) throw new Error(); const documentData=parseDocument(await response.text()); if(request !== profileRequest) return; document.querySelector("#about-content").innerHTML=renderMarkdown(documentData.content); applyProfile(documentData.fields); loadProjects(); } catch { if(request !== profileRequest) return; document.querySelector("#about-content").innerHTML=`<h2>${language === "ar" ? "عني" : "About me"}</h2>`; loadProjects(); } }
function setLanguage(next) { language=next; localStorage.setItem("portfolio-language",next); document.documentElement.lang=next; document.documentElement.dir=next === "ar" ? "rtl" : "ltr"; document.querySelector("#language-toggle").textContent=next === "ar" ? "EN" : "ع"; document.querySelectorAll("[data-i18n]").forEach(el=>el.textContent=t(el.dataset.i18n)); document.querySelectorAll("[data-i18n-html]").forEach(el=>el.innerHTML=t(el.dataset.i18nHtml)); loadAbout(); }
document.querySelector("#year").textContent=new Date().getFullYear(); document.querySelector("#language-toggle").addEventListener("click",()=>setLanguage(language === "ar" ? "en" : "ar")); setLanguage(language);
